/**
 * This file was auto-generated by the Titanium Module SDK helper for Android
 * Appcelerator Titanium Mobile
 * Copyright (c) 2009-present by Appcelerator, Inc. All Rights Reserved.
 * Licensed under the terms of the Apache Public License
 * Please see the LICENSE included with this distribution for details.
 *
 */
package ti.crashlytics;

import org.appcelerator.kroll.KrollModule;
import org.appcelerator.kroll.annotations.Kroll;

import com.google.firebase.crashlytics.FirebaseCrashlytics;

@Kroll.module(name="TitaniumCrashlytics", id="ti.crashlytics")
public class TitaniumCrashlyticsModule extends KrollModule
{
	// Methods

	@Kroll.method
	public void log(String message)
	{
		FirebaseCrashlytics.getInstance().log(message);
	}

	@Kroll.method
	public void crash() {
		throw new RuntimeException("This is a crash");
	}

	@Kroll.setProperty
	public void setUserId(String userId)
	{
		FirebaseCrashlytics.getInstance().setUserId(userId);
	}

	@Kroll.setProperty
	public void setCrashlyticsCollectionEnabled(boolean crashlyticsCollectionEnabled)
	{
		FirebaseCrashlytics.getInstance().setCrashlyticsCollectionEnabled(crashlyticsCollectionEnabled);
	}

	@Kroll.method
	public void recordError(KrollDict obj) {
		String description = obj.getString("description");
		String errorKey = obj.getString("key");
		String suggestion = obj.getString("suggestion");
		String exceptionMessage = "Description:" + description;

		if (errorKey != "") {
			exceptionMessage = exceptionMessage + " Error Key:" + errorKey;
		}

		if (suggestion != "") {
			exceptionMessage = exceptionMessage + " Suggestion:" + suggestion;
		}

		FirebaseCrashlytics.getInstance().recordException(new RuntimeException(exceptionMessage));
	}
}

